[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
block_wallet = "A77rXueYXYg3bJejEFRuQFv2bbV3sBhCZwotH4cy4HCX"

[programs.devnet]
block_wallet = "A77rXueYXYg3bJejEFRuQFv2bbV3sBhCZwotH4cy4HCX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=ed4cacb9-dfb0-49f2-b133-84d15a49a704"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
